### ISSUE TITLE
No new torrents appearing

### ISSUE THREAD

**Issue by duramato** [FlyersWeb/dhtbay#4]
I've tried setting this up with the instructions in the readme, but it isn't showing any new ones on bitcannon. What should i input in here https://github.com/FlyersWeb/dhtbay/blob/master/config/database.default.js#L3
if i didn't setup anything with mongodb?, just defaults, does it have any default login? Or do i make it blank? 
Currently i have it as `uri : 'mongodb://user:passwor@127.0.0.1:27017/bitcannon'`

**Comment by FlyersWeb** [comment]
Hi, you should have a mongodb server to store received torrents. When you'll have one, you'll have to rename database.default.json to database.json and provide your credentials.
Let me know if you have any troubles

**Comment by duramato** [comment]
Yes I already have mongodb installed and running for bitcannon,  but I don't what to input in the credentials, does mongodb come with any default ones? As I didn't set up any credentials on Mongo myself

**Comment by FlyersWeb** [comment]
As far as I know, there is no credentials installed with default mongo install, you'll just need to provide the host and port : `mongodb://localhost:27017/bitcannon`
You'll need to put it in a `database.json` file to work but be patient DHT may take some time to set the routing table.

**Comment by duramato** [comment]
I'm still not seeing anything showing up, are the `updateSeed.js` , `classifier.js` , `categorize.js` and `loadFileTorrent.js` needed? becouse i did every other step from the readme except running those 4 ones
Also are there any log files besides the aria one? i see aria working from its log file but don't know if there are other operations beeing executed correctly.

**Comment by duramato** [comment]
mm ok so i've found forever's logging and according to it its working? But nothing appears on bitcannon.
loadDHT: https://gist.github.com/duramato/b46b3585744b04c82cc169290841346c
crawlDHT: https://gist.github.com/duramato/3349d4b089eb9f129046b117404ef6a8

And bitcannon's db is empty: http://img.cla46.com/up/1467219258c340684.png

**Comment by FlyersWeb** [comment]
did you add the cron jobs as specified in the README ? Because loadDHT just download .torrent files to your file system, the `loadFileTorrent.js` actually fill the database.

**Comment by FlyersWeb** [comment]
`categorize.js`: will try to classify the torrent.
`updateSeed.js`: try to update seeds informations using trackers
`classifier.js`: will try to classify using probabilistic algorithm so it's not really mandatory

**Comment by duramato** [comment]
I didn't had it setup, i just setup the cron jobs now and it seems its working, at least they are showing on bitcannon.
I did try running them mannually to see if i could kickstart it and i got this

```
/usr/bin/node /root/dhtbay/updateSeed.js
Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead
[Fri, 01 Jul 2016 11:05:45 GMT] { '0': 'Stream closed' }
```

is that normal?

**Comment by FlyersWeb** [comment]
Sometimes it's not possible to connect to the tracker so the script don't do nothing, the update seed is optional anyway but it could be improved if you feel it, you can make a pull request :)

**Comment by duramato** [comment]
But is that just a methode depreceation warning, or something crucial? I just see them exiting when i try to run it, for example categorize.js exits without doing anything , and checking bitcannon i don't see any categories just the `Unknown` one

And also noticed this when running `classifier`:

```
/usr/bin/node classifier.js
Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead
[Fri, 01 Jul 2016 14:24:17 GMT] { '0': 'Treating 529757107b230cb4bfeecff918834691a9322858 categorization' }
/root/dhtbay/node_modules/mongoose/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'value' of undefined
    at QueryStream.<anonymous> (/root/dhtbay/classifier.js:61:30)
    at emitOne (events.js:77:13)
    at QueryStream.emit (events.js:169:7)
    at emit (/root/dhtbay/node_modules/mongoose/lib/querystream.js:276:8)
    at /root/dhtbay/node_modules/mongoose/lib/querystream.js:267:5
    at model.Document.init (/root/dhtbay/node_modules/mongoose/lib/document.js:295:5)
    at createAndEmit (/root/dhtbay/node_modules/mongoose/lib/querystream.js:263:12)
    at QueryStream._onNextObject (/root/dhtbay/node_modules/mongoose/lib/querystream.js:235:9)
    at cursorcb (/root/dhtbay/node_modules/mongoose/lib/querystream.js:186:11)
    at handleCallback (/root/dhtbay/node_modules/mongoose/node_modules/mongodb/lib/utils.js:96:12)
    at /root/dhtbay/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/root/dhtbay/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/root/dhtbay/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /root/dhtbay/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/root/dhtbay/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:241:5)
    at Callbacks.emit (/root/dhtbay/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
```

Categorize just does:

```
# nodejs categorize.js
Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead
```

**Comment by FlyersWeb** [comment]
You've found a bug in categorization, I've made a fix to resolve the issue let me know if it work.

**Comment by duramato** [comment]
It seems to be fixed, its working now, tested with `categorize.js` , `classifier.js` and even the trainer and all worked :)
`updateSeed.js` is the one that still gives the same thing and doesn't update any seeds (atleast i don't see any diff in the UI`
just: 

```
# nodejs updateSeed.js
Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead
[Fri, 01 Jul 2016 16:58:03 GMT] { '0': 'Stream closed' }
```

**Comment by FlyersWeb** [comment]
It must be because it cannot contact tracking servers to update seeds, it worked on 1 on 10 when I was running my crawler.
Let me know if you need any help create a new issue. Thanks for helping me to improve the software, remember that you can always make pull requests to the project.
Regards.

**Comment by duramato** [comment]
I just noticed aria2 randomly stopped, taking a look at its logs:

```
2016-07-05 10:29:38.787524 [NOTICE] [RequestGroupMan.cc:379] Download GID#0b2d6535914649b0 not complete:
2016-07-05 10:29:43.793993 [ERROR] [AbstractCommand.cc:312] CUID#429 - Download aborted. URI=http://torcache.net/torrent/53557A029BEA75BFE7CF92D18A227756F7194731.torrent
Exception: [AbstractCommand.cc:312] errorCode=22 URI=http://torcache.net/torrent/53557A029BEA75BFE7CF92D18A227756F7194731.torrent
  -> [HttpSkipResponseCommand.cc:228] errorCode=22 The response status is not successful. status=451
2016-07-05 10:29:43.794253 [NOTICE] [RequestGroupMan.cc:379] Download GID#2bf422a45e9f1e1e not complete:
2016-07-05 10:29:48.800182 [ERROR] [AbstractCommand.cc:312] CUID#431 - Download aborted. URI=http://torcache.net/torrent/53557A029BEA75BFE7CF92D18A227756F7194731.torrent
Exception: [AbstractCommand.cc:312] errorCode=22 URI=http://torcache.net/torrent/53557A029BEA75BFE7CF92D18A227756F7194731.torrent
  -> [HttpSkipResponseCommand.cc:228] errorCode=22 The response status is not successful. status=451
2016-07-05 10:29:48.800453 [NOTICE] [RequestGroupMan.cc:379] Download GID#a2ddd09ed7b7b834 not complete:
2016-07-05 10:29:51.559677 [NOTICE] [DownloadEngine.cc:251] Emergency shutdown sequence commencing...
```

What does that `Emergency shutdown sequence commencing` mean? can i enable more detailed logging?

**Comment by duramato** [comment]
Debug logs:

```
2016-07-06 15:20:52.299591 [DEBUG] [FeedbackURISelector.cc:84] FeedbackURISelector selected http://torcache.net/torrent/B55F7ABAD48005618CB6FAA1EFC8533A96FFF7BA.torrent
2016-07-06 15:20:52.299626 [DEBUG] [AbstractCommand.cc:147] CUID#89 - socket: read:0, write:0, hup:0, err:0
2016-07-06 15:20:52.299660 [INFO] [AbstractCommand.cc:767] CUID#89 - DNS cache hit: torcache.net -> 95.215.61.199, 109.163.226.148, 94.242.255.194
2016-07-06 15:20:52.299685 [INFO] [HttpInitiateConnectionCommand.cc:135] CUID#89 - Connecting to 95.215.61.199:80
2016-07-06 15:20:52.300999 [DEBUG] [WebSocketSessionMan.cc:64] WebSocket session removed.
2016-07-06 15:20:52.414065 [DEBUG] [AbstractCommand.cc:147] CUID#89 - socket: read:0, write:1, hup:0, err:0
2016-07-06 15:20:52.414199 [DEBUG] [AbstractCommand.cc:147] CUID#89 - socket: read:0, write:1, hup:0, err:0
2016-07-06 15:20:52.414280 [INFO] [HttpConnection.cc:116] CUID#89 - Requesting:
GET /torrent/B55F7ABAD48005618CB6FAA1EFC8533A96FFF7BA.torrent HTTP/1.1
User-Agent: aria2/1.18.1
Accept: */*,application/metalink4+xml,application/metalink+xml
Accept-Encoding: deflate, gzip
Host: torcache.net


2016-07-06 15:20:53.059069 [DEBUG] [AbstractCommand.cc:147] CUID#89 - socket: read:1, write:0, hup:0, err:0
2016-07-06 15:20:53.059230 [INFO] [HttpConnection.cc:153] CUID#89 - Response received:
HTTP/1.1 404 Not Found
Server: nginx
Date: Wed, 06 Jul 2016 15:20:52 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
X-Powered-By: PHP/7.0.6
Content-Encoding: gzip


2016-07-06 15:20:53.059291 [DEBUG] [AbstractCommand.cc:147] CUID#89 - socket: read:1, write:0, hup:0, err:0
2016-07-06 15:20:53.059380 [ERROR] [AbstractCommand.cc:312] CUID#89 - Download aborted. URI=http://torcache.net/torrent/B55F7ABAD48005618CB6FAA1EFC8533A96FFF7BA.torrent
Exception: [AbstractCommand.cc:312] errorCode=3 URI=http://torcache.net/torrent/B55F7ABAD48005618CB6FAA1EFC8533A96FFF7BA.torrent
  -> [HttpSkipResponseCommand.cc:215] errorCode=3 Resource not found
2016-07-06 15:20:53.059474 [DEBUG] [AbstractCommand.cc:435] CUID#89 - Aborting download
2016-07-06 15:20:53.059502 [DEBUG] [AbstractCommand.cc:385] CUID#89 - Not trying next request. No reserved/pooled request is remaining and total length is still unknown.
2016-07-06 15:20:53.059537 [DEBUG] [RequestGroup.cc:949] GID#76aac82158f0237e - Request queue check
2016-07-06 15:20:53.059736 [NOTICE] [RequestGroupMan.cc:379] Download GID#76aac82158f0237e not complete:
2016-07-06 15:20:53.059769 [DEBUG] [RequestGroup.cc:1141] GID#76aac82158f0237e - Creating DownloadResult.
2016-07-06 15:20:53.059825 [DEBUG] [RequestGroupMan.cc:416] 1 RequestGroup(s) deleted.
2016-07-06 15:22:09.070324 [NOTICE] [DownloadEngine.cc:251] Emergency shutdown sequence commencing...
```

**Comment by duramato** [comment]
I also noticed that running the loadFileTorrent, there are a bunch of `[Error: Invalid data: Missing delimiter ":" [0x3a]]`

```
# nodejs /root/dhtbay/loadFileTorrent.js
[Wed, 06 Jul 2016 22:12:54 GMT] { '0': [Error: Invalid data: Missing delimiter ":" [0x3a]] }
[Wed, 06 Jul 2016 22:12:54 GMT] { '0': [Error: Invalid data: Missing delimiter ":" [0x3a]] }
[Wed, 06 Jul 2016 22:12:54 GMT] { '0': 'treating file : /root/dhtbay/torrent/B55C802C36D6A380031FC3B0B728BF9C21FC2442.torrent' }
[Wed, 06 Jul 2016 22:12:54 GMT] { '0': [Error: Invalid data: Missing delimiter ":" [0x3a]] }.
[Wed, 06 Jul 2016 22:12:54 GMT] { '0': [Error: Invalid data: Missing delimiter ":" [0x3a]] }
[Wed, 06 Jul 2016 22:12:54 GMT] { '0': 'Torrent b55c802c36d6a380031fc3b0b728bf9c21fc2442 already present.' }
```

**Comment by FlyersWeb** [comment]
I had never seen the Emergency shutdown sequence before, maybe did you had a problem installing aria2, you may report this issue to them.

**Comment by FlyersWeb** [comment]
The Invalid delimiter error comes from bad formatted torrent files, I think the problem may come from aria2 not downloading properly the specified file. Anyway a torrent might appear a lot when you're on the same DHT node so it will be downloaded again, no worries it will be indexed
